apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-cert
  namespace: argocd
spec:
  project: cert
  source:
    repoURL: https://github.com/lizabethwordp/k8s-app-of-apps         # App-of-Apps repo
    targetRevision: cert
    path: apps/cert                                  # ✅ Only dev apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
