apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-qa
  namespace: argocd
spec:
  project: qa
  source:
    repoURL: https://github.com/lizabethwordp/k8s-app-of-apps         # App-of-Apps repo
    targetRevision: qa
    path: apps/qa                                # ✅ Only qa apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true


