apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert
  namespace: argocd
spec:
  description: Cert environment apps
  sourceRepos:
    - https://github.com/lizabethwordp/*        # App-of-Apps repo
  destinations:
    - namespace: cert
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
